name: Hydra nightly

on:
  schedule:
    # 00:00 UTC daily
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  # Our self-hosted runner is a systemd service, so child processes inherit
  # JOURNAL_STREAM. Clear it so that CI logs use the default colored format
  # instead of syslog priority prefixes meant for journald.
  JOURNAL_STREAM: ""

jobs:
  hydra_against_blockfrost_tests:
    name: Hydra tests of their `--blockfrost` option
    runs-on: [self-hosted, Linux, X64, nixos]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run Hydra Tests
        timeout-minutes: 15
        env:
          CARDANO_NODE_SOCKET_PATH: /run/cardano-node/node_preview.socket
          BLOCKFROST_PROJECT_ID: ${{ secrets.BLOCKFROST_TESTS_PROJECT_ID }}
          SUBMIT_MNEMONIC: ${{ secrets.BLOCKFROST_TESTS_SUBMIT_MNEMONIC }}
        run: |
          nix run -L .#internal.x86_64-linux.hydra-test

  hydra_platform_gateway_tests:
    name: Hydra micropayments tests between Platform↔Gateway
    runs-on: [self-hosted, Linux, X64, nixos]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run Hydra Tests
        timeout-minutes: 60
        env:
          CARDANO_NODE_SOCKET_PATH: /run/cardano-node/node_preview.socket
          BLOCKFROST_PROJECT_ID: ${{ secrets.BLOCKFROST_TESTS_PROJECT_ID }}
          SUBMIT_MNEMONIC: ${{ secrets.BLOCKFROST_TESTS_SUBMIT_MNEMONIC }}
        run: |
          nix run -L .#internal.x86_64-linux.hydra-platform-gateway-test

  hydra_bridge_gateway_tests:
    name: Hydra micropayments tests between Bridge↔Gateway
    runs-on: [self-hosted, Linux, X64, nixos]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run Hydra Tests
        timeout-minutes: 60
        env:
          CARDANO_NODE_SOCKET_PATH: /run/cardano-node/node_preview.socket
          BLOCKFROST_PROJECT_ID: ${{ secrets.BLOCKFROST_TESTS_PROJECT_ID }}
          SUBMIT_MNEMONIC: ${{ secrets.BLOCKFROST_TESTS_SUBMIT_MNEMONIC }}
        run: |
          nix run -L .#internal.x86_64-linux.hydra-bridge-gateway-test
